a = input("digite algo: ")
print("o tipo primitivo é ", type(a))
print("só tem espaços ? ", a.isspace())
print("é um número ? ", a.isnumeric())
print("é alfabético ? ",a.isalpha())
print("é alfanumérico ? ",a.isalnum())
print("está em maiúsculo ? ",a.isupper())
print("está em minúsculo ? ",a.islower())
print("está capitalizada ? ",a.istitle())
