nome = str(input("digite um nome: ")).strip()
ma = nome.upper()
mi = nome.lower()
le = (len(nome) - nome.count(' '))
#ql = (nome.find(" "))
pr1 = nome.split()
print("o nome em maiúscula é {} \n o nome em minusculo {} \n tem ao todo {} letra \n e o primeiro nome tem {} letras ".format(ma,mi,le,primeironome))
print("Seu primeiro nome é {} e ele tem {} letras".format(pr1[0],len(pr1[0]))) 